# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

FROM ubuntu:xenial

RUN apt-get update \
 && apt-get install -y -q --allow-downgrades \
    build-essential \
    software-properties-common \
    curl \
    libssl-dev \
    gcc \
    git \
    libzmq3-dev \
    openssl \
    pkg-config \
    unzip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD && \
    apt-add-repository "deb http://repo.sawtooth.me/ubuntu/bumper/stable xenial universe" && \
	apt-get update && \
	apt-get install -y python3-sawtooth-cli python3-sawtooth-intkey python3-sawtooth-poet-cli python3-sawtooth-poet-common python3-sawtooth-poet-core python3-sawtooth-poet-families python3-sawtooth-poet-simulator python3-sawtooth-rest-api python3-sawtooth-sdk python3-sawtooth-settings python3-sawtooth-signing python3-sawtooth-validator sawtooth-smallbank-tp-go python3-sawtooth-poet-engine python3-sawtooth-poet-sgx python3-sawtooth-ias-client python3-sawtooth-ias-proxy python3-sawtooth-identity python3-sawtooth-integration 

WORKDIR /project
